# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd7f61dbf734e0e19030eb9d5f7083ab1a9b5e07f20cb647ad44545bc8b85dd55e3cad1e05a8d8edd21bc7c244a689cf340d72227bb3c2c53eb217d9f2ce704

test:
  secret_key_base: 791e5832e7b29bf80d9bee2383a1e847b040a564295773efcd855009b616c141e8097583c9c53e9ee561c1dc872cbeb37cbd7ad7864a0ce6083e58fc4061a27d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
